<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-04T08:57:58 IST" name="Default suite" finished-at="2023-02-04T08:57:58 IST" duration-ms="70">
    <groups>
    </groups>
    <test started-at="2023-02-04T08:57:58 IST" name="Default test" finished-at="2023-02-04T08:57:58 IST" duration-ms="70">
      <class name="testNGKeywordsStudy.AlwaysTrueStudy">
        <test-method signature="verifyRegisteringAccountByFillMandatoryField()[pri:0, instance:testNGKeywordsStudy.AlwaysTrueStudy@2b662a77]" started-at="2023-02-04T08:57:58 IST" name="verifyRegisteringAccountByFillMandatoryField" finished-at="2023-02-04T08:57:58 IST" duration-ms="14" status="FAIL">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at testNGKeywordsStudy.AlwaysTrueStudy.verifyRegisteringAccountByFillMandatoryField(AlwaysTrueStudy.java:9)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyRegisteringAccountByFillMandatoryField -->
        <test-method signature="verifyLoginAccountByValidCredentials()[pri:0, instance:testNGKeywordsStudy.AlwaysTrueStudy@2b662a77]" started-at="2023-02-04T08:57:58 IST" name="verifyLoginAccountByValidCredentials" finished-at="2023-02-04T08:57:58 IST" depends-on-methods="testNGKeywordsStudy.AlwaysTrueStudy.verifyRegisteringAccountByFillMandatoryField" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginAccountByValidCredentials -->
      </class> <!-- testNGKeywordsStudy.AlwaysTrueStudy -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
